CREATE TABLE  FEE_Admin
   (	ID int auto_increment, 
	name VARCHAR(400), 
	email VARCHAR(400), 
	password VARCHAR(400), 
	city VARCHAR(400), 
	contact VARCHAR(400), 
	 CONSTRAINT FEE_ACCOUNTANT_PK PRIMARY KEY (ID)
   );


CREATE TABLE  FEE_STUDENT 
   (ROLLNO int auto_increment, 
	NAME VARCHAR(400), 
	EMAIL VARCHAR(400), 
	SEX VARCHAR(400), 
	COURSE VARCHAR(400), 
	FEE int, 
	PAID int, 
	DUE int, 
	ADDRESS VARCHAR(400), 
	CONTACT VARCHAR(400), 
	 CONSTRAINT FEE_STUDENT_PK PRIMARY KEY (ROLLNO)
   );


CREATE TABLE  FEE_ACCOUNTANT 
   (	ID int auto_increment, 
	NAME VARCHAR(400), 
	EMAIL VARCHAR(400), 
	PASSWORD VARCHAR(400), 
	ADDRESS VARCHAR(400), 
	CONTACT VARCHAR(400), 
	 CONSTRAINT FEE_ACCOUNTANT_PK PRIMARY KEY (ID)
   );
